/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Address = IDL.Record({
  'zip' : IDL.Text,
  'street' : IDL.Text,
  'gstNumber' : IDL.Text,
  'city' : IDL.Text,
  'email' : IDL.Text,
  'state' : IDL.Text,
  'phone' : IDL.Text,
});
export const CompanyHeader = IDL.Record({
  'bankDetails' : IDL.Record({
    'branch' : IDL.Text,
    'ifscCode' : IDL.Text,
    'gstNumber' : IDL.Text,
    'accountNumber' : IDL.Text,
    'accountHolder' : IDL.Text,
  }),
  'name' : IDL.Text,
  'bankUpi' : IDL.Text,
  'address' : Address,
});
export const CostRow = IDL.Record({
  'total' : IDL.Nat,
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
});
export const InvoiceStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'paid' : IDL.Null,
});
export const Time = IDL.Int;
export const Invoice = IDL.Record({
  'status' : InvoiceStatus,
  'materialCosts' : IDL.Vec(CostRow),
  'date' : Time,
  'declaration' : IDL.Text,
  'invoiceNumber' : IDL.Nat,
  'advanceAmount' : IDL.Nat,
  'shippedTo' : Address,
  'loadingCharges' : IDL.Nat,
  'companyHeader' : CompanyHeader,
  'shippingCharges' : IDL.Nat,
  'billTo' : Address,
  'fabricationCosts' : IDL.Vec(CostRow),
});

export const idlService = IDL.Service({
  'createInvoice' : IDL.Func(
      [
        CompanyHeader,
        Address,
        Address,
        IDL.Vec(CostRow),
        IDL.Vec(CostRow),
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
  'getInvoice' : IDL.Func([IDL.Nat], [Invoice], ['query']),
  'listInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'updateInvoice' : IDL.Func([IDL.Nat, Invoice], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Address = IDL.Record({
    'zip' : IDL.Text,
    'street' : IDL.Text,
    'gstNumber' : IDL.Text,
    'city' : IDL.Text,
    'email' : IDL.Text,
    'state' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CompanyHeader = IDL.Record({
    'bankDetails' : IDL.Record({
      'branch' : IDL.Text,
      'ifscCode' : IDL.Text,
      'gstNumber' : IDL.Text,
      'accountNumber' : IDL.Text,
      'accountHolder' : IDL.Text,
    }),
    'name' : IDL.Text,
    'bankUpi' : IDL.Text,
    'address' : Address,
  });
  const CostRow = IDL.Record({
    'total' : IDL.Nat,
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
  });
  const InvoiceStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'paid' : IDL.Null,
  });
  const Time = IDL.Int;
  const Invoice = IDL.Record({
    'status' : InvoiceStatus,
    'materialCosts' : IDL.Vec(CostRow),
    'date' : Time,
    'declaration' : IDL.Text,
    'invoiceNumber' : IDL.Nat,
    'advanceAmount' : IDL.Nat,
    'shippedTo' : Address,
    'loadingCharges' : IDL.Nat,
    'companyHeader' : CompanyHeader,
    'shippingCharges' : IDL.Nat,
    'billTo' : Address,
    'fabricationCosts' : IDL.Vec(CostRow),
  });
  
  return IDL.Service({
    'createInvoice' : IDL.Func(
        [
          CompanyHeader,
          Address,
          Address,
          IDL.Vec(CostRow),
          IDL.Vec(CostRow),
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
    'getInvoice' : IDL.Func([IDL.Nat], [Invoice], ['query']),
    'listInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'updateInvoice' : IDL.Func([IDL.Nat, Invoice], [], []),
  });
};

export const init = ({ IDL }) => { return []; };