/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'zip' : string,
  'street' : string,
  'gstNumber' : string,
  'city' : string,
  'email' : string,
  'state' : string,
  'phone' : string,
}
export interface CompanyHeader {
  'bankDetails' : {
    'branch' : string,
    'ifscCode' : string,
    'gstNumber' : string,
    'accountNumber' : string,
    'accountHolder' : string,
  },
  'name' : string,
  'bankUpi' : string,
  'address' : Address,
}
export interface CostRow {
  'total' : bigint,
  'description' : string,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export interface Invoice {
  'status' : InvoiceStatus,
  'materialCosts' : Array<CostRow>,
  'date' : Time,
  'declaration' : string,
  'invoiceNumber' : bigint,
  'advanceAmount' : bigint,
  'shippedTo' : Address,
  'loadingCharges' : bigint,
  'companyHeader' : CompanyHeader,
  'shippingCharges' : bigint,
  'billTo' : Address,
  'fabricationCosts' : Array<CostRow>,
}
export type InvoiceStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'paid' : null };
export type Time = bigint;
export interface _SERVICE {
  'createInvoice' : ActorMethod<
    [
      CompanyHeader,
      Address,
      Address,
      Array<CostRow>,
      Array<CostRow>,
      bigint,
      bigint,
      bigint,
      string,
    ],
    bigint
  >,
  'deleteInvoice' : ActorMethod<[bigint], undefined>,
  'getInvoice' : ActorMethod<[bigint], Invoice>,
  'listInvoices' : ActorMethod<[], Array<Invoice>>,
  'updateInvoice' : ActorMethod<[bigint, Invoice], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];