/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CompanyHeader {
    bankDetails: {
        branch: string;
        ifscCode: string;
        gstNumber: string;
        accountNumber: string;
        accountHolder: string;
    };
    name: string;
    bankUpi: string;
    address: Address;
}
export interface Invoice {
    status: InvoiceStatus;
    materialCosts: Array<CostRow>;
    date: Time;
    declaration: string;
    invoiceNumber: bigint;
    advanceAmount: bigint;
    shippedTo: Address;
    loadingCharges: bigint;
    companyHeader: CompanyHeader;
    shippingCharges: bigint;
    billTo: Address;
    fabricationCosts: Array<CostRow>;
}
export type Time = bigint;
export interface CostRow {
    total: bigint;
    description: string;
    quantity: bigint;
    unitPrice: bigint;
}
export interface Address {
    zip: string;
    street: string;
    gstNumber: string;
    city: string;
    email: string;
    state: string;
    phone: string;
}
export enum InvoiceStatus {
    cancelled = "cancelled",
    pending = "pending",
    paid = "paid"
}
export interface backendInterface {
    createInvoice(companyHeader: CompanyHeader, billTo: Address, shippedTo: Address, materialCosts: Array<CostRow>, fabricationCosts: Array<CostRow>, loadingCharges: bigint, shippingCharges: bigint, advanceAmount: bigint, declaration: string): Promise<bigint>;
    deleteInvoice(invoiceNumber: bigint): Promise<void>;
    getInvoice(invoiceNumber: bigint): Promise<Invoice>;
    listInvoices(): Promise<Array<Invoice>>;
    updateInvoice(invoiceNumber: bigint, invoiceData: Invoice): Promise<void>;
}
import type { Address as _Address, CompanyHeader as _CompanyHeader, CostRow as _CostRow, Invoice as _Invoice, InvoiceStatus as _InvoiceStatus, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createInvoice(arg0: CompanyHeader, arg1: Address, arg2: Address, arg3: Array<CostRow>, arg4: Array<CostRow>, arg5: bigint, arg6: bigint, arg7: bigint, arg8: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async deleteInvoice(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInvoice(arg0);
            return result;
        }
    }
    async getInvoice(arg0: bigint): Promise<Invoice> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_Invoice_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_Invoice_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async listInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInvoices();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInvoices();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateInvoice(arg0: bigint, arg1: Invoice): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoice(arg0, to_candid_Invoice_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoice(arg0, to_candid_Invoice_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_InvoiceStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceStatus): InvoiceStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Invoice_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invoice): Invoice {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _InvoiceStatus;
    materialCosts: Array<_CostRow>;
    date: _Time;
    declaration: string;
    invoiceNumber: bigint;
    advanceAmount: bigint;
    shippedTo: _Address;
    loadingCharges: bigint;
    companyHeader: _CompanyHeader;
    shippingCharges: bigint;
    billTo: _Address;
    fabricationCosts: Array<_CostRow>;
}): {
    status: InvoiceStatus;
    materialCosts: Array<CostRow>;
    date: Time;
    declaration: string;
    invoiceNumber: bigint;
    advanceAmount: bigint;
    shippedTo: Address;
    loadingCharges: bigint;
    companyHeader: CompanyHeader;
    shippingCharges: bigint;
    billTo: Address;
    fabricationCosts: Array<CostRow>;
} {
    return {
        status: from_candid_InvoiceStatus_n3(_uploadFile, _downloadFile, value.status),
        materialCosts: value.materialCosts,
        date: value.date,
        declaration: value.declaration,
        invoiceNumber: value.invoiceNumber,
        advanceAmount: value.advanceAmount,
        shippedTo: value.shippedTo,
        loadingCharges: value.loadingCharges,
        companyHeader: value.companyHeader,
        shippingCharges: value.shippingCharges,
        billTo: value.billTo,
        fabricationCosts: value.fabricationCosts
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    paid: null;
}): InvoiceStatus {
    return "cancelled" in value ? InvoiceStatus.cancelled : "pending" in value ? InvoiceStatus.pending : "paid" in value ? InvoiceStatus.paid : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Invoice>): Array<Invoice> {
    return value.map((x)=>from_candid_Invoice_n1(_uploadFile, _downloadFile, x));
}
function to_candid_InvoiceStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceStatus): _InvoiceStatus {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Invoice_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Invoice): _Invoice {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: InvoiceStatus;
    materialCosts: Array<CostRow>;
    date: Time;
    declaration: string;
    invoiceNumber: bigint;
    advanceAmount: bigint;
    shippedTo: Address;
    loadingCharges: bigint;
    companyHeader: CompanyHeader;
    shippingCharges: bigint;
    billTo: Address;
    fabricationCosts: Array<CostRow>;
}): {
    status: _InvoiceStatus;
    materialCosts: Array<_CostRow>;
    date: _Time;
    declaration: string;
    invoiceNumber: bigint;
    advanceAmount: bigint;
    shippedTo: _Address;
    loadingCharges: bigint;
    companyHeader: _CompanyHeader;
    shippingCharges: bigint;
    billTo: _Address;
    fabricationCosts: Array<_CostRow>;
} {
    return {
        status: to_candid_InvoiceStatus_n8(_uploadFile, _downloadFile, value.status),
        materialCosts: value.materialCosts,
        date: value.date,
        declaration: value.declaration,
        invoiceNumber: value.invoiceNumber,
        advanceAmount: value.advanceAmount,
        shippedTo: value.shippedTo,
        loadingCharges: value.loadingCharges,
        companyHeader: value.companyHeader,
        shippingCharges: value.shippingCharges,
        billTo: value.billTo,
        fabricationCosts: value.fabricationCosts
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    paid: null;
} {
    return value == InvoiceStatus.cancelled ? {
        cancelled: null
    } : value == InvoiceStatus.pending ? {
        pending: null
    } : value == InvoiceStatus.paid ? {
        paid: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
